title: C. Åleskog
author:
  name: Christoffer Åleskog
  email: christoffer.aleskog@gmail.com

# The `>` after `description:` means to ignore line-breaks until next key.
# If you want to omit the line-break after the end of text, use `>-` instead.
description: >
  This is the homepage for Christoffer Åleskog.

# Build settings

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme

remote_theme: jekyll/minima

paginate: 5
paginate_path: "/blog/page:num/"

# Theme-specific settings

minima:
  skin: auto

  social_links:
    - { platform: linkedin,       user_url: "https://www.linkedin.com/in/christoffer-Åleskog-885109184/" }
    - { platform: google_scholar, user_url: "https://scholar.google.com/citations?user=KIZVufAAAAAJ&hl=sv&oi=ao" }
    - { platform: github,       user_url: "https://github.com/caleskog" }
  
    
  # Minima date format.
  # Refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this.
  #
  # date_format: "%b %-d, %Y"

  # Generate social links in footer.
  #
  #   - { platform: devto,          user_url: "https://dev.to/jekyll" }
  #   - { platform: dribbble,       user_url: "https://dribbble.com/jekyll" }
  #   - { platform: facebook,       user_url: "https://www.facebook.com/jekyll" }
  #   - { platform: flickr,         user_url: "https://www.flickr.com/photos/jekyll" }
  #   - { platform: github,         user_url: "https://github.com/jekyll/minima" }
  #   - { platform: instagram,      user_url: "https://www.instagram.com/jekyll" }
  #   - { platform: keybase,        user_url: "https://keybase.io/jekyll" }
  #   - { platform: microdotblog,   user_url: "https://micro.blog/jekyll" }
  #   - { platform: pinterest,      user_url: "https://www.pinterest.com/jekyll" }
  #   - { platform: stackoverflow,  user_url: "https://stackoverflow.com/users/1234567/jekyll" }
  #   - { platform: telegram,       user_url: "https://t.me/jekyll" }
  #   - { platform: twitter,        user_url: "https://twitter.com/jekyllrb" }
  #   - { platform: youtube,        user_url: "https://www.youtube.com/jekyll" }

# If you want to link only specific pages in your header, uncomment this and add the path to the pages in
# order as they should show up.
#

header_pages:
  - about.md
  - publications.md
  - blog.md

include:
  - favicons

# Set to `true` to show excerpts on the homepage.
#
show_excerpts: false
